### ISSUE TITLE
Levantamento de frentes

### ISSUE THREAD

**Issue by Misterio77** [gelos-icmc/meta#2]

**Comment by CarlosCraveiro** [comment]
Ok, após uma breve olhada na [página de projetos do site](https://gelos.club/projetos/). Cheguei nesse levantamento inicial.

O status de todas está como desconhecido, pois a ideia é justamente saber como andam cada uma delas.

Se houverem frentes não mapeadas por esse levantamento inicial. Por favor comentem neste PR. Vou nos próximos dias caçar no telegram por frentes não formalizadas também.

| Frente        | Responsável    | Status Atual |
|--------------|-----------|------------|
| [Infraestrutura](https://gelos.club/projetos/infra.html) | @Misterio77       | Desconhecido |
|[Open Source Shows](https://gelos.club/projetos/opensource-shows.html) | @gp2112 | Desconhecido |
| [Plantões de Dúvidas](https://gelos.club/projetos/plantao.html) | Desconhecido | Desconhecido |
|[Contribuições FLOSS](https://gelos.club/projetos/contribuicoes.html)| @Misterio77  | Desconhecido |
|[Grupos de Estudo](https://gelos.club/projetos/grupos-de-estudo.html)| @Misterio77  | Desconhecido |

**Comment by CarlosCraveiro** [comment]
@Misterio77, poderia me informar o status das frentes de: **Infraestrutura**, **Contribuições FLOSS** e **Grupos de Estudo**?

**Comment by CarlosCraveiro** [comment]
@gp2112, poderia me informar o status da frente de **Open Source Shows**?

**Comment by CarlosCraveiro** [comment]
Alguém saberia me dizer quem é o responsável pelo **Plantões de Dúvidas**?

**Comment by CarlosCraveiro** [comment]
Ok, acabei de ver que a atribuição do **Plantões de Dúvidas** está na Issue gelos-icmc/site#70 do site. Mas acredito então que a atibuição esteja com @deandreson e @jul1co? Certo?

**Comment by Misterio77** [comment]
> @Misterio77, poderia me informar o status das frentes de: Infraestrutura, Contribuições FLOSS e Grupos de Estudo?

Respondido no telegram. Infra: ativo. Contribuições floss: em concepção. Grupos de Estudo pode deixar como ativo.

> Ok, acabei de ver que a atribuição do Plantões de Dúvidas está na Issue https://github.com/gelos-icmc/site/issues/70 do site. Mas acredito então que a atibuição esteja com @deandreson e @jul1co? Certo?{

Perfeito

**Comment by Misterio77** [comment]
> @gp2112, poderia me informar o status da frente de Open Source Shows?

Acho que podemos manter como atual. Está um pouco parado agora, mas a idéia é voltar.
